---
title: "Plot Andrea"
author: "Andrea Ceskova"
format: html
---

```{r}
#| label: setup

library(tidyverse)
library(gapminder)
data(gapminder)
data("continent_colors")
library(showtext)
library(ggrepel)

font_add_google("Source Sans 3", "source_sans")
font_add_google("Righteous", "righteous")

showtext_auto()

```

```{r}
#| label: fig-plot

germany <- gapminder %>%
  filter(year == 2007) %>%
  filter(country == "Germany")
  
ggplot(gapminder,
       aes( x =gdpPercap, y = lifeExp, col = continent)) +
  geom_point() +
  geom_label_repel(data = germany, aes(label = country)) +
  scale_y_log10() +
  scale_x_log10(labels = scales::comma) +
  scale_color_manual(values = continent_colors) +
  labs(x = "GDP per capita",
       y = "Life expectancy",
       caption = "data from gapminder") +
  theme_minimal() +
  theme(text = element_text(family = "source_sans", size = 25),
        plot.title = element_text(family = "righteous", size = 30),
        legend.position = "bottom",
        legend.text.position = "top")



  
```
