---
title: "Data wragling"
author: "Elvin Mammadov"
date: "2025-04-20"
output: html_document
---

```{r loading packages, include=FALSE}
#install.packages("summarytools")
#install.packages("devtools")

library(haven)
library(here)
library(stargazer)
library(summarytools)
library(readxl)
library(dplyr)
library(lubridate)
library(ggplot2)

#Vdem data 
devtools::install_github("vdeminstitute/vdemdata")
library(vdemdata)
vdem <- vdemdata::vdem


#opening datasets (individual survey)
unzip("Data/GPS_Dataset.zip")
unzip("GPS_dataset_individual_level.zip")
GPS_indiv <- read_dta(here("individual_new.dta"))

#opening datasets (country survey)
unzip(here("GPS_dataset_country_level.zip"))
GPS_country <- read_dta(here("Data", "country.dta"))

#openning data polity
p5 <- read_excel(here("Data", "p5v2018.xls"))


#converting the column encodings to UTF-8
names(GPS_indiv)
GPS_indiv <- GPS_indiv %>%
  mutate(across(where(is.character), ~ iconv(., from = "", to = "UTF-8")))




view(dfSummary(GPS_country))
view(dfSummary(GPS_indiv))
view(dfSummary(p5))
view(dfSummary(vdem))

#selecting necessary columns
vdem_sub <- vdem %>%
  select(country_name, year, v2x_libdem)

#calculating birt_years and selecting necessary columns
gps_sub <- GPS_indiv %>%
  mutate(birth_year = year(date) - age) %>%
  select(country, age, trust, patience, birth_year)


#creating regime change function
generate_regime_change <- function(data, threshold = 0.03) {
  data %>%
    arrange(country_name, year) %>%
    group_by(country_name) %>%
    mutate(
      libdem_diff = v2x_libdem - lag(v2x_libdem),
      regime_change = ifelse(libdem_diff > threshold, 1, 0)
    ) %>%
    ungroup()

}

#then applying this function to our data , *thershold* is example, this number can be different.

vdem_with_regimes <- generate_regime_change(vdem_sub, threshold = 0.03)

head(vdem_with_regimes)


#Imagine the person faced with democracy at 18
gps_sub <- gps_sub %>%
  mutate(year_at_18 = birth_year + 18)

#merging data
merged_data <- gps_sub %>%
  left_join(vdem_with_regimes, 
            by = c("country" = "country_name", "year_at_18" = "year"))


view(dfSummary(merged_data))


```


```{r plotting world map, echo=FALSE}




install.packages(c("tidyverse", "sf", "rnaturalearth", "rnaturalearthdata"))


library(tidyverse)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)



vdem_2018 <- vdem %>%
  filter(year == 2018) %>%
  select(country_name, country_text_id, year, v2x_libdem) 


world <- ne_countries(scale = "medium", returnclass = "sf")

# Merge map with V-Dem data
world_vdem <- world %>%
  left_join(vdem_2018, by = c("iso_a3" = "country_text_id"))

# Drawing the map
ggplot(data = world_vdem) +
  geom_sf(aes(fill = v2x_libdem), color = "gray70", size = 0.1) +
  scale_fill_viridis_c(name = "Liberal Democracy Index", na.value = "lightgray") +
  labs(
    title = "Liberal Democracy Index by Country (2018)",
    caption = "Data: V-Dem v14, World map: Natural Earth"
  ) +
  theme_minimal()


```




```{r}


# 1. Create age intervals starting from 15
gps_data <- merged_data %>%
  mutate(age_group = cut(age,
                         breaks = seq(15, 85, by = 10),
                         include.lowest = TRUE,
                         right = FALSE,
                         labels = paste(seq(15, 75, by = 10), seq(24, 84, by = 10), sep = "-")
                         ))

# 2. Calculate percentages
age_dist <- gps_data %>%
  count(age_group) %>%
  mutate(percent = 100 * n / sum(n))

# 3. Plot the histogram
ggplot(age_dist, aes(x = age_group, y = percent)) +
  geom_bar(stat = "identity", fill = "#009E73", color = "white") +
  labs(
    title = "Age Distribution of GPS Individuals",
    x = "Age Group",
    y = "Percentage (%)"
  ) +
  theme_minimal() +
  geom_text(aes(label = sprintf("%.1f%%", percent)), vjust = -0.3, size = 3.5)

```

